version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        networks:
            - app-network
        command: sh -c "php artisan config:clear && php artisan cache:clear && php artisan migrate && php artisan db:seed && php-fpm"

    db:
        image: mysql:8.0
        container_name: db
        restart: always
        environment:
            - MYSQL_HOST=db
            - MYSQL_PORT=3306
            - MYSQL_DATABASE=notebook_api
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - app-network

    web:
        image: nginx:latest
        container_name: web
        restart: always
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
